# Gateway Configuration - Stdout Emitter
server:
  http:
    host: "0.0.0.0"
    port: "8001"
    read_timeout: "30s"
    write_timeout: "30s"
    idle_timeout: "60s"
    bounds:
      max_batch: 1000
      max_message_bytes: 65536
    pipeline:
      enqueue_timeout: "5s"
  
  grpc:
    host: "0.0.0.0"
    port: "9090"
    max_batch: 1000
    max_concurrent_streams: 100
    max_connection_idle: "30s"
    max_connection_age: "60s"
    max_connection_age_grace: "10s"
    time: "5s"
    timeout: "1s"

otlp:
  max_log_size: 1048576      # 1MB
  max_batch_size: 1000       # 1000 logs per batch
  max_labels: 100            # 100 labels per log
  max_fields: 200            # 200 fields per log
  request_timeout: "30s"     # 30s timeout
  validate_utf8: true        # Validate UTF-8
  allowed_schemas: ["JSON", "LOGFMT", "TEXT"]

emitter:
  output_type: "stdout"      # stdout, kafka, grpc, forwarder
  batch_size: 100            # Batch size for output
  flush_interval: 5          # Flush interval in seconds
  # No forwarder configuration needed for stdout

metrics: {}
