apiVersion: 1

datasources:
  - name: Loki (Processed)
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: loki
          matcherRegex: "traceID=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"

  - name: Loki (Raw)
    type: loki
    access: proxy
    url: http://loki-raw:3100
    isDefault: false
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: loki-raw
          matcherRegex: "traceID=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"

