# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from indexfeed.v1 import indexfeed_pb2 as indexfeed_dot_v1_dot_indexfeed__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in indexfeed/v1/indexfeed_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CandidateIngestStub(object):
    """----------------------------- gRPC surface (optional) ------------------------
    Use this if you choose gRPC between Gateway and Python Event-Builder.
    For Kafka/Redpanda, publish TemplateCandidateBatch messages to a topic with
    partition key (tenant + ":" + template_id).

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Publish = channel.unary_unary(
                '/indexcandidate.v1.CandidateIngest/Publish',
                request_serializer=indexfeed_dot_v1_dot_indexfeed__pb2.TemplateCandidateBatch.SerializeToString,
                response_deserializer=indexfeed_dot_v1_dot_indexfeed__pb2.PublishAck.FromString,
                _registered_method=True)


class CandidateIngestServicer(object):
    """----------------------------- gRPC surface (optional) ------------------------
    Use this if you choose gRPC between Gateway and Python Event-Builder.
    For Kafka/Redpanda, publish TemplateCandidateBatch messages to a topic with
    partition key (tenant + ":" + template_id).

    """

    def Publish(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CandidateIngestServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=indexfeed_dot_v1_dot_indexfeed__pb2.TemplateCandidateBatch.FromString,
                    response_serializer=indexfeed_dot_v1_dot_indexfeed__pb2.PublishAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'indexcandidate.v1.CandidateIngest', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('indexcandidate.v1.CandidateIngest', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CandidateIngest(object):
    """----------------------------- gRPC surface (optional) ------------------------
    Use this if you choose gRPC between Gateway and Python Event-Builder.
    For Kafka/Redpanda, publish TemplateCandidateBatch messages to a topic with
    partition key (tenant + ":" + template_id).

    """

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/indexcandidate.v1.CandidateIngest/Publish',
            indexfeed_dot_v1_dot_indexfeed__pb2.TemplateCandidateBatch.SerializeToString,
            indexfeed_dot_v1_dot_indexfeed__pb2.PublishAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
