// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: indexfeed/v1/indexfeed.proto

package indexcandidatev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CandidateIngest_Publish_FullMethodName = "/indexcandidate.v1.CandidateIngest/Publish"
)

// CandidateIngestClient is the client API for CandidateIngest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CandidateIngestClient interface {
	Publish(ctx context.Context, in *TemplateCandidateBatch, opts ...grpc.CallOption) (*PublishAck, error)
}

type candidateIngestClient struct {
	cc grpc.ClientConnInterface
}

func NewCandidateIngestClient(cc grpc.ClientConnInterface) CandidateIngestClient {
	return &candidateIngestClient{cc}
}

func (c *candidateIngestClient) Publish(ctx context.Context, in *TemplateCandidateBatch, opts ...grpc.CallOption) (*PublishAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishAck)
	err := c.cc.Invoke(ctx, CandidateIngest_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CandidateIngestServer is the server API for CandidateIngest service.
// All implementations must embed UnimplementedCandidateIngestServer
// for forward compatibility.
type CandidateIngestServer interface {
	Publish(context.Context, *TemplateCandidateBatch) (*PublishAck, error)
	mustEmbedUnimplementedCandidateIngestServer()
}

// UnimplementedCandidateIngestServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCandidateIngestServer struct{}

func (UnimplementedCandidateIngestServer) Publish(context.Context, *TemplateCandidateBatch) (*PublishAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedCandidateIngestServer) mustEmbedUnimplementedCandidateIngestServer() {}
func (UnimplementedCandidateIngestServer) testEmbeddedByValue()                         {}

// UnsafeCandidateIngestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CandidateIngestServer will
// result in compilation errors.
type UnsafeCandidateIngestServer interface {
	mustEmbedUnimplementedCandidateIngestServer()
}

func RegisterCandidateIngestServer(s grpc.ServiceRegistrar, srv CandidateIngestServer) {
	// If the following call pancis, it indicates UnimplementedCandidateIngestServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CandidateIngest_ServiceDesc, srv)
}

func _CandidateIngest_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TemplateCandidateBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CandidateIngestServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CandidateIngest_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CandidateIngestServer).Publish(ctx, req.(*TemplateCandidateBatch))
	}
	return interceptor(ctx, in, info, handler)
}

// CandidateIngest_ServiceDesc is the grpc.ServiceDesc for CandidateIngest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CandidateIngest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "indexcandidate.v1.CandidateIngest",
	HandlerType: (*CandidateIngestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _CandidateIngest_Publish_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "indexfeed/v1/indexfeed.proto",
}
