# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/v1/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63ommon/v1/common.proto\x12\tcommon.v1\"Y\n\x08\x45xemplar\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0b\n\x03pod\x18\x02 \x01(\t\x12\x11\n\tnamespace\x18\x03 \x01(\t\x12\x0c\n\x04node\x18\x04 \x01(\t\x12\x0e\n\x06stream\x18\x05 \x01(\t\"F\n\x0cWindowCounts\x12\x11\n\tcount_10m\x18\x01 \x01(\x04\x12\x10\n\x08\x63ount_1h\x18\x02 \x01(\x04\x12\x11\n\tcount_24h\x18\x03 \x01(\x04*U\n\x06Schema\x12\x16\n\x12SCHEMA_UNSPECIFIED\x10\x00\x12\x0f\n\x0bSCHEMA_JSON\x10\x01\x12\x11\n\rSCHEMA_LOGFMT\x10\x02\x12\x0f\n\x0bSCHEMA_TEXT\x10\x03*\x86\x01\n\x08Severity\x12\x18\n\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x12\n\x0eSEVERITY_DEBUG\x10\x01\x12\x11\n\rSEVERITY_INFO\x10\x02\x12\x11\n\rSEVERITY_WARN\x10\x03\x12\x12\n\x0eSEVERITY_ERROR\x10\x04\x12\x12\n\x0eSEVERITY_FATAL\x10\x05*F\n\x06\x41\x63tion\x12\x16\n\x12\x41\x43TION_UNSPECIFIED\x10\x00\x12\x0f\n\x0b\x41\x43TION_KEEP\x10\x01\x12\x13\n\x0f\x41\x43TION_SUPPRESS\x10\x02*\xd0\x01\n\nKeepReason\x12\x1b\n\x17KEEP_REASON_UNSPECIFIED\x10\x00\x12\x18\n\x14KEEP_REASON_SEVERITY\x10\x01\x12\x15\n\x11KEEP_REASON_NOVEL\x10\x02\x12\x15\n\x11KEEP_REASON_SPIKE\x10\x03\x12\x16\n\x12KEEP_REASON_WARMUP\x10\x04\x12\x14\n\x10KEEP_REASON_LOG2\x10\x05\x12\x17\n\x13KEEP_REASON_STEADYK\x10\x06\x12\x16\n\x12KEEP_REASON_BUDGET\x10\x07*s\n\x11TemplateEventType\x12#\n\x1fTEMPLATE_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x10\n\x0cTEMPLATE_NEW\x10\x01\x12\x13\n\x0fTEMPLATE_UPDATE\x10\x02\x12\x12\n\x0eTEMPLATE_SPIKE\x10\x03\x42\x42Z@github.com/kumarabd/ingestion-plane/contracts/common/v1;commonv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z@github.com/kumarabd/ingestion-plane/contracts/common/v1;commonv1'
  _globals['_SCHEMA']._serialized_start=200
  _globals['_SCHEMA']._serialized_end=285
  _globals['_SEVERITY']._serialized_start=288
  _globals['_SEVERITY']._serialized_end=422
  _globals['_ACTION']._serialized_start=424
  _globals['_ACTION']._serialized_end=494
  _globals['_KEEPREASON']._serialized_start=497
  _globals['_KEEPREASON']._serialized_end=705
  _globals['_TEMPLATEEVENTTYPE']._serialized_start=707
  _globals['_TEMPLATEEVENTTYPE']._serialized_end=822
  _globals['_EXEMPLAR']._serialized_start=37
  _globals['_EXEMPLAR']._serialized_end=126
  _globals['_WINDOWCOUNTS']._serialized_start=128
  _globals['_WINDOWCOUNTS']._serialized_end=198
# @@protoc_insertion_point(module_scope)
