{{- if .Values.planner.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ingestion-plane.fullname" . }}-planner
  labels:
    {{- include "ingestion-plane.planner.labels" . | nindent 4 }}
  {{- with .Values.planner.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.planner.service.type }}
  ports:
  - port: {{ .Values.planner.service.grpcPort }}
    targetPort: grpc
    protocol: TCP
    name: grpc
  selector:
    {{- include "ingestion-plane.planner.selectorLabels" . | nindent 4 }}
{{- end }}

