# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: search/v1/search.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'search/v1/search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16search/v1/search.proto\x12\tsearch.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x02\n\rSemanticQuery\x12\r\n\x05query\x18\x01 \x01(\t\x12?\n\x0clabel_filter\x18\x02 \x03(\x0b\x32).search.v1.SemanticQuery.LabelFilterEntry\x12.\n\nstart_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_time\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05top_k\x18\x05 \x01(\r\x1a\x32\n\x10LabelFilterEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xa3\x02\n\x0bTemplateHit\x12\x13\n\x0btemplate_id\x18\x01 \x01(\t\x12\x10\n\x08template\x18\x02 \x01(\t\x12\r\n\x05regex\x18\x03 \x01(\t\x12\x32\n\x06labels\x18\x04 \x03(\x0b\x32\".search.v1.TemplateHit.LabelsEntry\x12\r\n\x05score\x18\x05 \x01(\x02\x12\x11\n\tcount_24h\x18\x06 \x01(\x04\x12,\n\x08ts_first\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07ts_last\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"6\n\x0eSearchResponse\x12$\n\x04hits\x18\x01 \x03(\x0b\x32\x16.search.v1.TemplateHit\"\x95\x01\n\x0bPlanRequest\x12(\n\x08selected\x18\x01 \x03(\x0b\x32\x16.search.v1.TemplateHit\x12.\n\nstart_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"(\n\x0cPlanResponse\x12\x18\n\x10logql_candidates\x18\x01 \x03(\t2\x87\x01\n\rSearchService\x12=\n\x06Search\x12\x18.search.v1.SemanticQuery\x1a\x19.search.v1.SearchResponse\x12\x37\n\x04Plan\x12\x16.search.v1.PlanRequest\x1a\x17.search.v1.PlanResponseBBZ@github.com/kumarabd/ingestion-plane/contracts/search/v1;searchv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search.v1.search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z@github.com/kumarabd/ingestion-plane/contracts/search/v1;searchv1'
  _globals['_SEMANTICQUERY_LABELFILTERENTRY']._loaded_options = None
  _globals['_SEMANTICQUERY_LABELFILTERENTRY']._serialized_options = b'8\001'
  _globals['_TEMPLATEHIT_LABELSENTRY']._loaded_options = None
  _globals['_TEMPLATEHIT_LABELSENTRY']._serialized_options = b'8\001'
  _globals['_SEMANTICQUERY']._serialized_start=71
  _globals['_SEMANTICQUERY']._serialized_end=327
  _globals['_SEMANTICQUERY_LABELFILTERENTRY']._serialized_start=277
  _globals['_SEMANTICQUERY_LABELFILTERENTRY']._serialized_end=327
  _globals['_TEMPLATEHIT']._serialized_start=330
  _globals['_TEMPLATEHIT']._serialized_end=621
  _globals['_TEMPLATEHIT_LABELSENTRY']._serialized_start=576
  _globals['_TEMPLATEHIT_LABELSENTRY']._serialized_end=621
  _globals['_SEARCHRESPONSE']._serialized_start=623
  _globals['_SEARCHRESPONSE']._serialized_end=677
  _globals['_PLANREQUEST']._serialized_start=680
  _globals['_PLANREQUEST']._serialized_end=829
  _globals['_PLANRESPONSE']._serialized_start=831
  _globals['_PLANRESPONSE']._serialized_end=871
  _globals['_SEARCHSERVICE']._serialized_start=874
  _globals['_SEARCHSERVICE']._serialized_end=1009
# @@protoc_insertion_point(module_scope)
