# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: miner/v1/miner.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'miner/v1/miner.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from contracts.ingest.v1 import ingest_pb2 as ingest_dot_v1_dot_ingest__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14miner/v1/miner.proto\x12\x08miner.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16ingest/v1/ingest.proto\";\n\x0e\x41nalyzeRequest\x12)\n\x07records\x18\x01 \x03(\x0b\x32\x18.ingest.v1.NormalizedLog\"\xa4\x02\n\x0eTemplateResult\x12\x14\n\x0crecord_index\x18\x01 \x01(\x05\x12\x13\n\x0btemplate_id\x18\x02 \x01(\t\x12\x10\n\x08template\x18\x03 \x01(\t\x12\r\n\x05regex\x18\x04 \x01(\t\x12\x17\n\x0fgroup_signature\x18\x05 \x01(\t\x12\x12\n\nconfidence\x18\x06 \x01(\x02\x12(\n\nprovenance\x18\x07 \x01(\x0e\x32\x14.miner.v1.Provenance\x12.\n\nfirst_seen\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12-\n\tlast_seen\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08\x65xamples\x18\n \x03(\t\"Q\n\x0bMinerShadow\x12\x14\n\x0crecord_index\x18\x01 \x01(\x05\x12,\n\ncandidates\x18\x02 \x03(\x0b\x32\x18.miner.v1.TemplateResult\"d\n\x0f\x41nalyzeResponse\x12)\n\x07results\x18\x01 \x03(\x0b\x32\x18.miner.v1.TemplateResult\x12&\n\x07shadows\x18\x02 \x03(\x0b\x32\x15.miner.v1.MinerShadow*\x8a\x01\n\nProvenance\x12\x1a\n\x16PROVENANCE_UNSPECIFIED\x10\x00\x12\x14\n\x10PROVENANCE_CACHE\x10\x01\x12\x18\n\x14PROVENANCE_HEURISTIC\x10\x02\x12\x17\n\x13PROVENANCE_LIBRELOG\x10\x03\x12\x17\n\x13PROVENANCE_FALLBACK\x10\x04\x32N\n\x0cMinerService\x12>\n\x07\x41nalyze\x12\x18.miner.v1.AnalyzeRequest\x1a\x19.miner.v1.AnalyzeResponseB@Z>github.com/kumarabd/ingestion-plane/contracts/miner/v1;minerv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'miner.v1.miner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z>github.com/kumarabd/ingestion-plane/contracts/miner/v1;minerv1'
  _globals['_PROVENANCE']._serialized_start=633
  _globals['_PROVENANCE']._serialized_end=771
  _globals['_ANALYZEREQUEST']._serialized_start=91
  _globals['_ANALYZEREQUEST']._serialized_end=150
  _globals['_TEMPLATERESULT']._serialized_start=153
  _globals['_TEMPLATERESULT']._serialized_end=445
  _globals['_MINERSHADOW']._serialized_start=447
  _globals['_MINERSHADOW']._serialized_end=528
  _globals['_ANALYZERESPONSE']._serialized_start=530
  _globals['_ANALYZERESPONSE']._serialized_end=630
  _globals['_MINERSERVICE']._serialized_start=773
  _globals['_MINERSERVICE']._serialized_end=851
# @@protoc_insertion_point(module_scope)
