# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ingest/v1/ingest.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ingest/v1/ingest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from contracts.common.v1 import common_pb2 as common_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16ingest/v1/ingest.proto\x12\tingest.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16\x63ommon/v1/common.proto\"\xe9\x03\n\rNormalizedLog\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x34\n\x06labels\x18\x02 \x03(\x0b\x32$.ingest.v1.NormalizedLog.LabelsEntry\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x34\n\x06\x66ields\x18\x04 \x03(\x0b\x32$.ingest.v1.NormalizedLog.FieldsEntry\x12!\n\x06schema\x18\x05 \x01(\x0e\x32\x11.common.v1.Schema\x12%\n\x08severity\x18\x06 \x01(\x0e\x32\x13.common.v1.Severity\x12\x11\n\tsanitized\x18\x07 \x01(\x08\x12\x17\n\x0foriginal_length\x18\x08 \x01(\r\x12\x11\n\ttruncated\x18\t \x01(\x08\x12-\n\tredaction\x18\n \x01(\x0b\x32\x1a.ingest.v1.RedactionReport\x12\x16\n\x0e\x63orrelation_id\x18\x0b \x01(\t\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a-\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"@\n\x0fRedactionReport\x12\x0f\n\x07\x61pplied\x18\x01 \x01(\x08\x12\r\n\x05rules\x18\x02 \x03(\t\x12\r\n\x05\x63ount\x18\x03 \x01(\r\"?\n\x12NormalizedLogBatch\x12)\n\x07records\x18\x01 \x03(\x0b\x32\x18.ingest.v1.NormalizedLog\"\x16\n\x03\x41\x63k\x12\x0f\n\x07message\x18\x01 \x01(\t2F\n\rIngestService\x12\x35\n\x04Push\x12\x1d.ingest.v1.NormalizedLogBatch\x1a\x0e.ingest.v1.AckBBZ@github.com/kumarabd/ingestion-plane/contracts/ingest/v1;ingestv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ingest.v1.ingest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z@github.com/kumarabd/ingestion-plane/contracts/ingest/v1;ingestv1'
  _globals['_NORMALIZEDLOG_LABELSENTRY']._loaded_options = None
  _globals['_NORMALIZEDLOG_LABELSENTRY']._serialized_options = b'8\001'
  _globals['_NORMALIZEDLOG_FIELDSENTRY']._loaded_options = None
  _globals['_NORMALIZEDLOG_FIELDSENTRY']._serialized_options = b'8\001'
  _globals['_NORMALIZEDLOG']._serialized_start=95
  _globals['_NORMALIZEDLOG']._serialized_end=584
  _globals['_NORMALIZEDLOG_LABELSENTRY']._serialized_start=492
  _globals['_NORMALIZEDLOG_LABELSENTRY']._serialized_end=537
  _globals['_NORMALIZEDLOG_FIELDSENTRY']._serialized_start=539
  _globals['_NORMALIZEDLOG_FIELDSENTRY']._serialized_end=584
  _globals['_REDACTIONREPORT']._serialized_start=586
  _globals['_REDACTIONREPORT']._serialized_end=650
  _globals['_NORMALIZEDLOGBATCH']._serialized_start=652
  _globals['_NORMALIZEDLOGBATCH']._serialized_end=715
  _globals['_ACK']._serialized_start=717
  _globals['_ACK']._serialized_end=739
  _globals['_INGESTSERVICE']._serialized_start=741
  _globals['_INGESTSERVICE']._serialized_end=811
# @@protoc_insertion_point(module_scope)
